# Generated by Django 2.2.2 on 2019-07-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_to_date', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('center_formation', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=800)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='date_to_date',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(default='SOME STRING', max_length=800),
        ),
    ]
