# Generated by Django 2.2.2 on 2019-07-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190701_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='center_formation',
        ),
    ]
