# Generated by Django 2.2.2 on 2019-07-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_formation_center_formation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('center_formation', models.CharField(max_length=100)),
                ('date_to_date', models.CharField(max_length=20)),
                ('body', models.TextField(max_length=800)),
            ],
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
    ]
