# Generated by Django 2.2.3 on 2019-07-07 16:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190706_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='body',
        ),
        migrations.AddField(
            model_name='skills',
            name='summary',
            field=ckeditor.fields.RichTextField(default='SOME STRING', max_length=800),
        ),
    ]
