# Generated by Django 2.2.3 on 2019-07-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20190707_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='summary',
            field=models.TextField(),
        ),
    ]
