# Generated by Django 2.2 on 2019-06-30 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_pub', models.DateField(default=datetime.datetime(2019, 6, 30, 10, 19, 32, 218380, tzinfo=utc))),
                ('body', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
