# Generated by Django 2.2.2 on 2019-06-30 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_pub',
            field=models.DateField(default=datetime.datetime(2019, 6, 30, 12, 9, 9, 519064, tzinfo=utc)),
        ),
    ]
