# Generated by Django 2.2.2 on 2019-07-01 14:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190701_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('center_formation', models.CharField(max_length=100)),
                ('date_to_date', models.CharField(max_length=20)),
                ('body', models.TextField(max_length=800)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_pub',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 14, 20, 30, 712469, tzinfo=utc)),
        ),
    ]
