# Generated by Django 2.2.2 on 2019-07-01 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190701_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_pub',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 14, 25, 49, 87623, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='formations',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
