# Generated by Django 2.2.2 on 2019-07-01 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190701_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formations',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_pub',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 14, 33, 28, 544808, tzinfo=utc)),
        ),
    ]
