# Generated by Django 2.2.3 on 2019-07-03 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190703_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_pub',
            field=models.DateField(default=datetime.datetime(2019, 7, 3, 11, 50, 14, 370134, tzinfo=utc)),
        ),
    ]
