# Generated by Django 2.2.3 on 2019-07-06 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190703_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_pub',
            field=models.DateField(default=datetime.datetime(2019, 7, 6, 18, 28, 42, 172230, tzinfo=utc)),
        ),
    ]
