# Generated by Django 2.2.3 on 2019-07-07 16:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190706_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_pub',
            field=models.DateField(default=datetime.datetime(2019, 7, 7, 16, 47, 35, 591068, tzinfo=utc)),
        ),
    ]
